#!/usr/bin/perl
#
# CSV to H
#
# CSV format
# filename,line, type, ID, C, Ja_JP, fr_FR, 
#
print "/* generated by cvs2msg.pl. do not edit this */\n";
print "#ifndef INCLUDE_OPENPTS_MSG_H_\n";
print "#define INCLUDE_OPENPTS_MSG_H_\n";

print "#define MF_OPENPTS \"openpts\"\n";
print "#define MS_OPENPTS 0\n";

$i=0;
while(<>) {
    chomp;
    my @m = split(/,/, $_);
    if ($m[3] ne "") {
        printf("#define %s  %d\n", $m[3], $i);
        $i++;
    }

}


print "#endif  // INCLUDE_OPENPTS_MSG_H_\n";
